server:
  port: 8004


spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pay?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    #向注册中心注册自己 true 不向注册中心注册自己 false
    register-with-eureka: true
    #是否让EurekaServer注册中心抓取自己的信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8004
    prefer-ip-address: true


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lxc.springcloud.entities
